[general]

# Repository to manage
repo=/mnt/Astro/SharedKStars

# If git fetch fails:
# false = ask the user
# true  = continue automatically
continue_without_fetch=false

[kstars]

path=/usr/bin/kstars

